# Generated by Django 2.2.4 on 2020-06-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200605_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='group',
            field=models.CharField(choices=[('U', 'User'), ('A', 'Admin'), ('E', 'Editor')], default='U', max_length=1),
        ),
    ]
